import Link from "next/link";
import { crystals } from "../lib/lunara";
import { ELEMENT_META } from "../lib/lunara-energy";

const elements=(Object.keys(ELEMENT_META) as (keyof typeof ELEMENT_META)[]);
export default function Home(){return <main>
<header className="nav shell"><Link className="brand" href="/">LUNARA</Link><nav><a href="#elements">Elements</a><a href="#library">Library</a><a href="#mine">The Mine</a><Link className="nav-cta" href="/reading">Begin your reading</Link></nav></header>
<section className="lux-hero shell"><div className="hero-copy"><p className="eyebrow">LUNARA · ELEMENTAL RITUAL</p><h1>Come back to what feels true.</h1><p className="lead">A quiet, modern ritual inspired by the Five Elements — designed to help you reflect, discover your current energy and meet a crystal that resonates with your intention.</p><div className="hero-actions"><Link className="button button-dark" href="/reading">Discover my elements <span>→</span></Link><a className="text-link" href="#ritual">Explore LUNARA ↓</a></div><p className="micro">3 minutes · No account required · For reflection & entertainment</p></div><div className="lux-hero-art"><div className="moon-glow"></div><div className="moon"></div><div className="stone-stack"><span>✦</span><span>◈</span><span>◎</span></div><p>QUIET MYSTICISM</p></div></section>
<section id="ritual" className="image-break"><div className="image-break-copy"><p className="eyebrow">A MOMENT INWARD</p><h2>Not fortune-telling.<br/>A ritual of reflection.</h2><p>Keep what resonates. Leave what does not. LUNARA uses symbolism as a beautiful prompt to pause, notice and choose.</p><Link className="text-link light-link" href="/reading">Begin your reading →</Link></div></section>
<section id="elements" className="section cream"><div className="shell"><div className="section-head"><p className="eyebrow">THE FIVE ELEMENTS</p><h2>Five qualities. One personal balance.</h2><p>Explore the elemental language behind the LUNARA experience, then take the reading to discover which themes are most present for you now.</p></div><div className="element-grid">{elements.map((e,i)=><article className={`element-card el-${e.toLowerCase()}`} key={e}><span className="element-index">0{i+1}</span><b>{ELEMENT_META[e].symbol}</b><h3>{e}</h3><p>{ELEMENT_META[e].theme}</p><Link href="/reading">Explore →</Link></article>)}</div></div></section>
<section className="section shell" id="library"><div className="section-head row"><div><p className="eyebrow">THE CRYSTAL LIBRARY</p><h2>Natural objects, chosen with intention.</h2></div><Link className="text-link" href="/shop">View collection →</Link></div><div className="product-grid">{crystals.slice(0,6).map(c=><Link className="product-card" key={c.slug} href={`/product/${c.slug}`}><div className={`product-art photo-art element-${c.element.toLowerCase()}`}><img src={c.image} alt={`${c.name} crystal`} /><span>{c.element}</span></div><div className="product-meta"><div><h3>{c.name}</h3><p>{c.tagline}</p></div><strong>${c.price}</strong></div></Link>)}</div></section>
<section className="editorial shell"><div className="editorial-art"><div>☾</div></div><div><p className="eyebrow">YOUR PERSONAL MATCH</p><h2>The crystal comes after the reflection.</h2><p>We first listen to your answers, then connect your dominant and supporting themes to a small, intentional edit of stones. The result is a personal ritual, not a generic shopping list.</p><Link className="button button-dark" href="/reading">Find my crystal →</Link></div></section>
<section id="mine" className="mine-section"><div className="shell mine-inner"><div><p className="eyebrow">THE LUNARA MINE</p><h2>Unearth the unexpected.</h2><p>A 350g natural raw + tumbled crystal discovery, designed as a tactile little ritual of curiosity.</p><Link className="button button-light" href="/shop">Explore the Mine →</Link></div><div className="mine-art"><span>350g</span><small>NATURAL STONE DISCOVERY</small></div></div></section>
<section className="journal shell"><div className="section-head"><p className="eyebrow">THE JOURNAL</p><h2>Notes on stones, symbolism & slow rituals.</h2></div><div className="journal-grid"><article><span>01 · ELEMENTS</span><h3>Why the Five Elements still feel relevant.</h3><p>A modern introduction to an ancient symbolic framework.</p></article><article><span>02 · CRYSTALS</span><h3>Raw or tumbled: which form feels right?</h3><p>Two ways to keep a natural stone close.</p></article><article><span>03 · RITUAL</span><h3>A five-minute ritual for a noisy day.</h3><p>Less performance. More presence.</p></article></div></section>
<section className="dark-cta shell"><div><p className="eyebrow">YOUR MOMENT IS HERE</p><h2>What are you ready to understand?</h2></div><Link className="button button-light" href="/reading">Start the ritual →</Link></section>
<footer className="footer shell"><div><Link className="brand" href="/">LUNARA</Link><p>Ancient symbolism, modern reflection.</p></div><div className="footer-links"><Link href="/reading">Reading</Link><Link href="/shop">Shop</Link><a href="#">Privacy</a><a href="#">Terms</a></div><p className="copyright">© 2026 LUNARA · For reflection and entertainment.</p></footer>
</main>}
