export type EnergyKey="protection"|"healing"|"love"|"wealth"|"growth";
export type ElementKey="Wood"|"Fire"|"Earth"|"Metal"|"Water";
export const ENERGY_META:Record<EnergyKey,{label:string;archetype:string;crystal:string;slug:string;description:string;element:ElementKey;theme:string}>= {
 protection:{label:"Protection",archetype:"The Guardian",crystal:"Black Obsidian",slug:"black-obsidian",description:"Grounding, boundaries, and a stronger sense of inner steadiness.",element:"Water",theme:"Protection"},
 healing:{label:"Healing",archetype:"The Quiet Tide",crystal:"Amethyst",slug:"amethyst",description:"Rest, reflection, emotional softness, and making space to reset.",element:"Water",theme:"Calm"},
 love:{label:"Love",archetype:"The Heart",crystal:"Rose Quartz",slug:"rose-quartz",description:"Connection, self-kindness, openness, and heart-led intention.",element:"Wood",theme:"Love"},
 wealth:{label:"Wealth",archetype:"The Golden Root",crystal:"Citrine",slug:"citrine",description:"Confidence around opportunity, action, and creating abundance.",element:"Earth",theme:"Abundance"},
 growth:{label:"Growth",archetype:"The Spark",crystal:"Carnelian",slug:"carnelian",description:"Courage, momentum, curiosity, and moving into a new chapter.",element:"Fire",theme:"Growth"}
};
export const ELEMENT_META:Record<ElementKey,{symbol:string;theme:string;description:string;crystals:string[]}>= {
 Wood:{symbol:"❋",theme:"Growth · Renewal · Possibility",description:"Wood represents renewal, movement and the quiet courage to grow beyond an old shape.",crystals:["Green Phantom Quartz","Rose Quartz"]},
 Fire:{symbol:"◈",theme:"Passion · Confidence · Expression",description:"Fire represents vitality, courage and the impulse to bring an intention into motion.",crystals:["Carnelian","Tiger's Eye"]},
 Earth:{symbol:"◎",theme:"Stability · Abundance · Grounding",description:"Earth represents steadiness, embodiment and the patience to build something lasting.",crystals:["Citrine","Tiger's Eye"]},
 Metal:{symbol:"✦",theme:"Clarity · Focus · Intention",description:"Metal represents discernment, precision and the clean edge of knowing what matters.",crystals:["Clear Quartz","White Agate"]},
 Water:{symbol:"☾",theme:"Intuition · Emotion · Protection",description:"Water represents intuition, emotional depth and the space to soften without losing your boundaries.",crystals:["Amethyst","Black Obsidian"]}
};
export const COMBINATIONS:Record<string,{title:string;text:string}>= {
 "protection-healing":{title:"The Grounded Healer",text:"You may be craving calm without losing your sense of boundaries."},"protection-love":{title:"The Protected Heart",text:"Your heart wants connection, but it also wants safety and clear boundaries."},"protection-wealth":{title:"The Secure Builder",text:"You are drawn toward creating stability before taking your next big step."},"protection-growth":{title:"The Resilient Explorer",text:"You have a strong instinct to protect yourself while still moving forward."},
 "healing-protection":{title:"The Quiet Guardian",text:"Rest and grounding appear to be the foundation for your next chapter."},"healing-love":{title:"The Gentle Heart",text:"Your current energy favors softness, recovery, and more compassionate connection."},"healing-wealth":{title:"The Restored Abundance",text:"You may be rebuilding your sense of worth and making room for healthier abundance."},"healing-growth":{title:"The Renewed Explorer",text:"A period of recovery may be preparing you for a meaningful change."},
 "love-protection":{title:"The Boundaried Heart",text:"Connection matters, but your strongest relationships also need healthy boundaries."},"love-healing":{title:"The Healing Heart",text:"Your heart may be asking for tenderness, acceptance, and emotional renewal."},"love-wealth":{title:"The Abundant Heart",text:"You are most energized when ambition and genuine feeling move in the same direction."},"love-growth":{title:"The Growing Heart",text:"Love, curiosity, and personal expansion are currently intertwined."},
 "wealth-protection":{title:"The Grounded Achiever",text:"You want progress that feels secure, practical, and sustainable."},"wealth-healing":{title:"The Balanced Achiever",text:"Your ambition works best when you also protect time for restoration."},"wealth-love":{title:"The Heart-Led Achiever",text:"You are motivated by achievement that feels personally meaningful."},"wealth-growth":{title:"The Ambitious Builder",text:"You have a strong appetite for momentum, opportunity, and measurable progress."},
 "growth-protection":{title:"The Fearless Guardian",text:"You are learning how to move boldly without abandoning your need for security."},"growth-healing":{title:"The Renewed Warrior",text:"A fresh beginning is easier when you allow yourself to recover along the way."},"growth-love":{title:"The Brave Heart",text:"You are being invited to grow while staying open to genuine connection."},"growth-wealth":{title:"The Abundance Seeker",text:"Opportunity and expansion are major themes in the way you are approaching your next chapter."}
};
export const QUESTIONS=[
 {q:"When life feels uncertain, what do you naturally seek first?",options:[["A quiet, protected space","protection"],["Time to rest and process","healing"],["Someone I trust","love"],["A practical plan for money or work","wealth"],["A new direction or challenge","growth"]]},
 {q:"Which result would feel most valuable right now?",options:[["Feeling grounded","protection"],["Feeling restored","healing"],["Feeling connected","love"],["Feeling financially confident","wealth"],["Feeling brave enough to change","growth"]]},
 {q:"Your ideal evening is...",options:[["Home, calm, and private","protection"],["A bath, music, and early night","healing"],["Dinner with someone special","love"],["Planning tomorrow's goals","wealth"],["Trying somewhere or something new","growth"]]},
 {q:"Which word pulls you in most?",options:[["Boundaries","protection"],["Renewal","healing"],["Connection","love"],["Abundance","wealth"],["Courage","growth"]]},
 {q:"When making a big decision, you trust...",options:[["What keeps me safe","protection"],["What feels emotionally right after reflection","healing"],["My heart and relationships","love"],["The opportunity and numbers","wealth"],["The possibility of what comes next","growth"]]},
 {q:"What would you most like to release?",options:[["Other people's energy","protection"],["Old emotional weight","healing"],["Fear of being misunderstood","love"],["Scarcity thinking","wealth"],["Fear of starting over","growth"]]},
 {q:"Which environment feels most restorative?",options:[["A quiet room","protection"],["Nature and soft light","healing"],["A warm gathering","love"],["A beautiful, productive workspace","wealth"],["A new city or landscape","growth"]]},
 {q:"Your current season feels most like...",options:[["Protecting what I have","protection"],["Recovering","healing"],["Opening my heart","love"],["Building something","wealth"],["Changing direction","growth"]]},
 {q:"Which gift would you choose?",options:[["A protective talisman","protection"],["A calming ritual set","healing"],["A heartfelt keepsake","love"],["A lucky abundance token","wealth"],["A travel/adventure experience","growth"]]},
 {q:"What makes you feel powerful?",options:[["Knowing my limits","protection"],["Knowing myself","healing"],["Giving and receiving love","love"],["Creating results","wealth"],["Doing something I once feared","growth"]]},
 {q:"If your energy had a texture, it would be...",options:[["Deep and grounded","protection"],["Soft and flowing","healing"],["Warm and gentle","love"],["Bright and magnetic","wealth"],["Golden and alive","growth"]]},
 {q:"What do you want more of?",options:[["Stability","protection"],["Peace","healing"],["Intimacy","love"],["Opportunity","wealth"],["Momentum","growth"]]},
 {q:"What drains you fastest?",options:[["Chaos and intrusion","protection"],["Emotional overload","healing"],["Disconnection","love"],["Feeling stuck financially","wealth"],["Repetition and stagnation","growth"]]},
 {q:"Which ritual sounds most appealing?",options:[["Cleansing your space","protection"],["Meditation and journaling","healing"],["Heart-opening reflection","love"],["Writing an abundance intention","wealth"],["Setting a bold new intention","growth"]]},
 {q:"When you imagine the next 6 months, you want to feel...",options:[["Secure","protection"],["Lighter","healing"],["Loved","love"],["Prosperous","wealth"],["Expanded","growth"]]},
 {q:"Which symbol attracts you?",options:[["A shield","protection"],["A moon","healing"],["A heart","love"],["A sun","wealth"],["A path","growth"]]},
 {q:"Your strongest hidden quality may be...",options:[["Resilience","protection"],["Sensitivity","healing"],["Empathy","love"],["Resourcefulness","wealth"],["Adaptability","growth"]]},
 {q:"What do you want your future self to thank you for?",options:[["Protecting my peace","protection"],["Taking care of myself","healing"],["Choosing meaningful relationships","love"],["Building financial options","wealth"],["Having the courage to change","growth"]]},
 {q:"If you could instantly improve one area, it would be...",options:[["Confidence in my boundaries","protection"],["Emotional balance","healing"],["Relationships","love"],["Money and career","wealth"],["Personal direction","growth"]]},
 {q:"Choose the sentence that feels most like your intention today.",options:[["I choose safety and grounding.","protection"],["I choose rest and renewal.","healing"],["I choose love and openness.","love"],["I choose abundance and action.","wealth"],["I choose courage and growth.","growth"]]}
] as const;
export function scoreAnswers(answers:string[]){const scores:Record<EnergyKey,number>={protection:0,healing:0,love:0,wealth:0,growth:0};answers.forEach((key,i)=>{if(key in scores)scores[key as EnergyKey]+=i===QUESTIONS.length-1?3:2});const ranked=(Object.keys(scores) as EnergyKey[]).sort((a,b)=>scores[b]-scores[a]);return {scores,dominant:ranked[0],secondary:ranked[1]};}
export function combination(dominant:EnergyKey,secondary:EnergyKey){return COMBINATIONS[`${dominant}-${secondary}`]??{title:`${ENERGY_META[dominant].archetype} + ${ENERGY_META[secondary].archetype}`,text:"Your result blends two complementary energies. Use this as a reflective prompt for your next step."};}
