"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { crystals } from "../../lib/lunara";

type Cart={slug:string;qty:number};
export default function Checkout(){
 const [product,setProduct]=useState<typeof crystals[number]|null>(null); const [qty,setQty]=useState(1); const [done,setDone]=useState(false); const [orderId,setOrderId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({email:"",name:"",address:"",city:"",postalCode:"",country:""});
 useEffect(()=>{const raw=localStorage.getItem("lunara-cart");if(raw){try{const x:Cart=JSON.parse(raw);setProduct(crystals.find(c=>c.slug===x.slug)||null);setQty(Math.max(1,x.qty||1))}catch{}}},[]);
 const total=product?product.price*qty:0;
 function set(k:keyof typeof form,v:string){setForm(f=>({...f,[k]:v}))}
 async function submit(){setError("");if(!product)return;setBusy(true);try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,slug:product.slug,product:product.name,qty,total})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to place order");await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.email,name:form.name,status:"purchased",source:"checkout",recommendedCrystals:[product.name]})});localStorage.removeItem("lunara-cart");setOrderId(data.order.id);setDone(true)}catch(e){setError(e instanceof Error?e.message:"Unable to place order.")}finally{setBusy(false)}}
 if(done)return <main><header className="nav shell"><Link className="brand" href="/">LUNARA</Link></header><section className="success shell"><div className="success-mark">✦</div><p className="eyebrow">RITUAL CONFIRMED</p><h1>Thank you.</h1><p>Your demo order <strong>{orderId}</strong> has been recorded in the private customer center.</p><p className="micro">This prototype does not charge a real payment method or create a real shipment. Connect Shopify Payments/Stripe before launch.</p><Link className="button button-dark" href="/">Return to LUNARA →</Link></section></main>;
 return <main><header className="nav shell"><Link className="brand" href="/">LUNARA</Link><Link href="/cart">← Cart</Link></header><section className="checkout shell"><div><p className="eyebrow">CHECKOUT</p><h1>Complete your ritual.</h1>{product?<div className="checkout-form"><label>Email<input required type="email" value={form.email} onChange={e=>set("email",e.target.value)} placeholder="you@example.com"/></label><label>Full name<input required value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Your name"/></label><label>Shipping address<input required value={form.address} onChange={e=>set("address",e.target.value)} placeholder="Street address"/></label><div className="two"><label>City<input required value={form.city} onChange={e=>set("city",e.target.value)} placeholder="City"/></label><label>Postal code<input required value={form.postalCode} onChange={e=>set("postalCode",e.target.value)} placeholder="Postal code"/></label></div><label>Country<input required value={form.country} onChange={e=>set("country",e.target.value)} placeholder="Country"/></label><div className="demo-note">Demo checkout · No real payment is collected.</div>{error&&<p className="form-error">{error}</p>}<button className="button button-dark full" disabled={busy} onClick={submit}>{busy?"Creating order…":"Place demo order →"}</button></div>:<div className="empty-card"><h2>Your cart is empty.</h2><Link className="button button-dark" href="/shop">Explore the collection →</Link></div>}</div><aside className="summary checkout-summary"><span>YOUR ORDER</span>{product?<><div className="summary-product"><span className="summary-photo"><img src={product.image} alt="" /></span><div><b>{product.name}</b><p>Qty {qty}</p></div><strong>${total.toFixed(2)}</strong></div><div className="summary-total"><p>Total</p><b>${total.toFixed(2)}</b></div></>:<p>Your cart is empty.</p>}</aside></section></main>;
}
